---
# tasks file for ansible-role-install-pkg-ubuntu
- include_vars: "main.yml"

- name: "Gather facts"
  setup:    # equivalent to "gather_facts: yes"

- name: "Update apt package cache"
  apt:
    cache_valid_time: 1200

- name: "Make sure {{ manage_pkg_dependency|length }} needed deb packages are installed"
  apt:
    name: "{{ manage_pkg_dependency }}"
    state: present

- name: "{{ 'Add' if manage_pkg_key_do == 'present' else 'Remove' }} {{ manage_pkg_key|length }} keys to authenticate deb trusted packages"
  apt_key:
    url: "{{ item }}"
    state: "{{ manage_pkg_key_do }}"
  with_items: "{{ manage_pkg_key }}"

- name: "{{ 'Add' if manage_pkg_repo_do == 'present' else 'Remove' }} {{ manage_pkg_repo|length }} apt repositories"
  apt_repository:
    repo: "{{ item }}"
    state: "{{ manage_pkg_repo_do }}"
  with_items: "{{ manage_pkg_repo }}"
  # PPAs somtimes return an HTTP 503 error
  # Play stubborn here to give it more chances to get executed
  retries: 5
  delay: 15

- name: "Refresh apt package cache for new repos"
  apt:
    cache_valid_time: 1200

- name: "{{ 'Add' if manage_pkg_app_do == 'present' else 'Remove' }} {{ manage_pkg_app|length }} deb packages"
  apt:
    name: "{{ manage_pkg_app }}"
    state: "{{ manage_pkg_app_do }}"
    install_recommends: "{{ manage_pkg_app_install_recommends }}"
